// <auto-generated />
using DigifyCXIntranet.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DigifyCXIntranet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610120000_RoleHardeningCanteenFinance")]
    partial class RoleHardeningCanteenFinance
    {
    }
}
